---
  - name: Install bash and completion
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - bash
      - bash-completion2

  - name: Add bash path to /private/etc/shells
    lineinfile:
      dest: /private/etc/shells
      line: '/usr/local/bin/bash'
    become: yes
